
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/<database>
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDBDialect
